name: GrassConflicts
version: '${version}'
main: com.github.gameoholic.grassconflicts.GrassConflictsPlugin
api-version: 1.19
authors: [ Gameoholic ]
description: Grass Conflicts
commands:
  start:
    description: Starts
    usage: /start
  test:
    description: Test
    usage: /test